// import { Registry as StyledJSXRegistry } from "./ui/styled-jsx/registry"
// import { Registry as StyledComponentRegistry } from "./ui/styled-components/Registry"
import { Registry as EmotionRootStyleRegistry } from "./ui/emotion/Registry"
import "./globals.css"
import { Inter } from "next/font/google"
import { Navigation } from "./ui/Navigation"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const links: Array<{ href: string; key: string }> = [
  {
    href: "/",
    key: "home",
  },
  {
    href: "/post",
    key: "post",
  },
  {
    href: "/dashboard",
    key: "dashboard",
  },
  {
    href: "/guides",
    key: "guides",
  },
  {
    href: "/shop",
    key: "shop",
  },
  {
    href: "/login",
    key: "login",
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EmotionRootStyleRegistry>
          <header>
            <div>
              <Navigation links={links} />
            </div>
          </header>
          <main>{children}</main>
          <footer className="bg-gray-200 py-4">
            <div className="container mx-auto px-4">
              <p className="text-center text-gray-600">
                &copy; {new Date().getFullYear()} Shopping Mall. All rights
                reserved.
              </p>
            </div>
          </footer>
        </EmotionRootStyleRegistry>
      </body>
    </html>
  )
}
